/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://ub4huklpfvhmpkqusgj33zh5na.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b2xoovqrvfa7npukpjfkhlodya",
    "aws_user_pools_id" : "NON_LO_SO",
    "aws_user_pools_web_client_id" : "NON_LO_SO_2"
};


export default awsConfig;
