/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: "us-west-1",
  aws_appsync_graphqlEndpoint:
    "https://ub4huklpfvhmpkqusgj33zh5na.appsync-api.us-west-1.amazonaws.com/graphql",
  aws_appsync_region: "us-west-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_cognito_identity_pool_id:
    "us-west-1:7a893998-439a-4c21-b471-6525d0454330",
  aws_cognito_region: "us-west-1",
  aws_user_pools_id: "us-west-1_tsGPzuncP",
  aws_user_pools_web_client_id: "2sd8irdkf01rs64acto8titdgg",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsConfig;
